baseURL: "https://guaniunotes.github.io/"
languageCode: "zh-cn"
title: "蜗牛笔记"
theme: PaperMod

hasCJKLanguage: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-KQLC070TT8

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 蜗牛笔记
  description: "全栈工程师，喜爱古典音乐，摄影，植物，崇尚道法自然。"
  keywords: [Blog, Portfolio, PaperMod]
  author: 蜗牛
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  TocSide: 'right'  # or 'right'

  ShowFullTextinRSS: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "logo.svg"
    favicon16x16: "logo.svg"
    favicon32x32: "logo.svg"
    apple_touch_icon: "logo.svg"
    safari_pinned_tab: "logo.svg"

  label:
    text: "蜗牛笔记"
    icon: "logo.svg"
    iconHeight: 35
    iconWidth: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: 蜗牛笔记
    subtitle: ""
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "大家好，我是蜗牛\U0001F44B"
    Content: 一名全栈工程师，喜爱古典音乐，摄影，植物，崇尚道法自然。

  socialIcons:
    - name: twitter
      url: "https://twitter.com/guaniuzz"
    - name: rss
      url: "index.xml"
    - name: instagram
    #  url: "https://github.com/"

  analytics:
   # google:
   #  SiteVerificationTag: "G-KQLC070TT8"
   # bing:
   #   SiteVerificationTag: "XYZabc"
   # yandex:
   #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    responsiveImages: false


  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]      

menu:
  main:
    - identifier: Archive
      name: archives
      url: archives
      weight: 5
    - identifier: Search
      name: search
      url: search/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

buildfuture: true
